networks:
  usmile:
    driver: bridge

services:
  bot:
    image: coder80/usmile
    container_name: usmile
    build:
      context: .
      dockerfile: Dockerifle
    env_file: .env
    profiles:
      - prod
    networks:
      - usmile

  bot-dev:
    container_name: usmile-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    profiles:
      - dev
    networks:
      - usmile
    volumes:
      - ./src:/usr/src/app/src

  postgres:
    image: postgres:17.4-alpine
    container_name: usmile-postgres
    networks:
      - usmile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: usmile
