networks:
  usmile:
    driver: bridge

services:
  bot:
    image: coder80/usmile
    container_name: usmile
    build:
      context: .
      dockerfile: Dockerifle
    env_file: .env
    profiles:
      - prod
    networks:
      - usmile
    restart: unless-stopped

  bot-dev:
    container_name: usmile-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    profiles:
      - dev
    networks:
      - usmile
    volumes:
      - ./src:/usr/src/app/src
    restart: unless-stopped

  postgres:
    image: postgres:17.4-alpine
    container_name: usmile-postgres
    networks:
      - usmile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: usmile
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --username=$$POSTGRES_USER --dbname usmile
      start_period: 10s
      start_interval: 1s
