FROM pypy:3

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir
RUN pip install watchdog[watchmedo] --no-cache-dir

CMD watchmedo auto-restart --patterns="*.py" --recursive --interval 5 -- pypy -u src/main.py
