FROM pypy:3

RUN apt update && apt install inkscape -y
RUN pip install watchdog[watchmedo] --no-cache-dir

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir

CMD watchmedo auto-restart --patterns="*.py" --recursive --interval 5 -- pypy -u src/main.py
