FROM python:3.12-alpine

WORKDIR /usr/src/app

RUN pip install watchdog
COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir

CMD watchmedo auto-restart --patterns="*.py" --recursive -- python -u src/main.py
