FROM pypy:3

WORKDIR /usr/src/app

RUN pip install flake8 --no-cache-dir 
COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir 
COPY . .

CMD ["python", "-m", "flake8", "./src"]
