apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certs-claim
  labels:
    app: usmile
    component: main
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: usmile-certs
---
apiVersion: v1
kind: Service
metadata:
  name: main-podname
  labels:
    app: usmile
    component: main
spec:
  ports:
    - port: 80
      targetPort: podname
  selector:
    app: usmile
    component: main
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
  labels:
    app: usmile
    component: main
spec:
  selector:
    matchLabels:
      app: usmile
      component: main
  template:
    metadata:
      labels:
        app: usmile
        component: main
    spec:
      volumes:
        - name: certs-volume
          persistentVolumeClaim:
            claimName: certs-claim
      containers:
        - name: main
          image: coder80/usmile:latest
          ports:
            - containerPort: 3000
              name: podname
          envFrom:
            - secretRef:
                name: secret
          env:
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_PORT
              value: !!str 5432
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: redis-service
          volumeMounts:
            - name: certs-volume
              mountPath: /usr/src/app/certs
          livenessProbe:
            httpGet:
              port: 3000
              path: liveness
            periodSeconds: 3
            initialDelaySeconds: 5
          startupProbe:
            httpGet:
              port: 3000
              path: liveness
            periodSeconds: 3
            failureThreshold: 20
